### ISSUE TITLE
missing file pius/auto-opt.h 

### ISSUE THREAD

**Issue by coguin** [petabi/regexbench#53]
Hi,  
When I make the project , it shows that can't find the file, pius/auto-opt.h And I can't find the file in the Internet and my computer.  Is it possible for you to send me the file Or tell me where to find the file? 
Thanks advance.

**Comment by minshao** [comment]
pull request #54 should fix the issue, could you please try again with the tip of develop and see if it compiles on your side?

**Comment by coguin** [comment]
It can compile OK now. Thanks a lot.
But I see pcre_check is unavailable,  Does it affect the function of other modules?

**Comment by minshao** [comment]
You are welcome and it won't affect other parts.
